version: "3"
services:
  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium
    ports:
      - "4444:4444"

  bot:
    build: .
    container_name: flatfinderbot
    depends_on:
      - selenium
    environment:
      - API_TOKEN=${API_TOKEN}
