# Dockerfile.quick
FROM selenium/standalone-chrome:latest

WORKDIR /app

# copy requirements
COPY requirements.txt . 
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

CMD ["python", "mergeBots.py"]
